services:
  postgres:
    image: postgres:17
    container_name: mobilemed-db
    environment:
      POSTGRES_USER: muka
      POSTGRES_PASSWORD: desafio
      POSTGRES_DB: mobilemed
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: